var resourceDiv=document.createElement('div')
resourceDiv.id="resourceDiv"
document.body.appendChild(resourceDiv)
//base function use for each course
function CourseName(){

    var nameDiv=document.createElement('div')
    nameDiv.id='nameDiv'
    resourceDiv.appendChild(nameDiv)

    var a=document.createElement('a')
    a.id='a'
    nameDiv.appendChild(a)

    var link=document.createTextNode("Description here")
    a.appendChild(link)
    a.href = "link"; 

    var nameDiv=document.createElement('div')
    nameDiv.id='nameDiv'
    resourceDiv.appendChild(nameDiv)

    var a=document.createElement('a')
    a.id='a'
    nameDiv.appendChild(a)

    var link=document.createTextNode("Description here")
    a.appendChild(link)
    a.href = "link"; 

}
CourseName()
function ENG4U(){
 
    var ENG4UDiv=document.createElement('div')
    ENG4UDiv.id='ENG4UDiv'
    resourceDiv.appendChild(ENG4UDiv)
 
    var a=document.createElement('a')
    a.id='a'
    ENG4UDiv.appendChild(a)
 
    var link=document.createTextNode("Tips for analyzing essays")
    a.appendChild(link)
    a.href = "https://sites.google.com/site/fungeng4u/tips-for-writing-a-literary-analysis-essay ";
 
    var ENG4UDiv=document.createElement('div')
    ENG4UDiv.id='ENG4UDiv'
    resourceDiv.appendChild(ENG4UDiv)
 
    var a=document.createElement('a')
    a.id='a'
    ENG4UDiv.appendChild(a)
 
    var link=document.createTextNode("Poetry guide")
    a.appendChild(link)
    a.href = "http://www.teachenglishtoday.org/wp-content/uploads/2018/07/Notes-on-Grade-12-HL-poems-2.pdf";

    var ENG4UDiv=document.createElement('div')
    ENG4UDiv.id='ENG4UDiv'
    resourceDiv.appendChild(ENG4UDiv)
 
    var a=document.createElement('a')
    a.id='a'
    ENG4UDiv.appendChild(a)
 
    var link=document.createTextNode("How to read Shakespeare")
    a.appendChild(link)
    a.href = "https://www.bardweb.net/content/ac/shakesreader.html ";

    var ENG4UDiv=document.createElement('div')
    ENG4UDiv.id='ENG4UDiv'
    resourceDiv.appendChild(ENG4UDiv)
 
    var a=document.createElement('a')
    a.id='a'
    ENG4UDiv.appendChild(a)
 
    var link=document.createTextNode("How to read academic writing")
    a.appendChild(link)
    a.href = "https://libguides.usc.edu/evaluate/scholarlyarticles ";

    var ENG4UDiv=document.createElement('div')
    ENG4UDiv.id='ENG4UDiv'
    resourceDiv.appendChild(ENG4UDiv)
 
    var a=document.createElement('a')
    a.id='a'
    ENG4UDiv.appendChild(a)
 
    var link=document.createTextNode("ISU book ideas")
    a.appendChild(link)
    a.href = "http://iss.scdsb.on.ca/Documents/Library%20Documents/Senior-ISU-Book-ListWEB.pdf ";
 
}

function ETS4U(){
 
    var ETS4UDiv=document.createElement('div')
    ETS4UDiv.id='ETS4UDiv'
    resourceDiv.appendChild(ETS4UDiv)
 
    var a=document.createElement('a')
    a.id='a'
    ETS4UDiv.appendChild(a)
 
    var link=document.createTextNode("Bible overview")
    a.appendChild(link)
    a.href = "https://overviewbible.com/books-of-the-bible/ ";
 
    var ETS4UDiv=document.createElement('div')
    ETS4UDiv.id='ETS4UDiv'
    resourceDiv.appendChild(ETS4UDiv)
 
    var a=document.createElement('a')
    a.id='a'
    ETS4UDiv.appendChild(a)
 
    var link=document.createTextNode("Guide to post-apocalyptic fiction")
    a.appendChild(link)
    a.href = "https://www.masterclass.com/articles/what-is-apocalyptic-and-post-apocalyptic-fiction ";

    var ETS4UDiv=document.createElement('div')
    ETS4UDiv.id='ETS4UDiv'
    resourceDiv.appendChild(ETS4UDiv)
 
    var a=document.createElement('a')
    a.id='a'
    ETS4UDiv.appendChild(a)
 
    var link=document.createTextNode("Guide to reading sci-fi")
    a.appendChild(link)
    a.href = "https://www.nypl.org/blog/2019/01/02/beginners-guide-science-fiction ";

    var ETS4UDiv=document.createElement('div')
    ETS4UDiv.id='ETS4UDiv'
    resourceDiv.appendChild(ETS4UDiv)
 
    var a=document.createElement('a')
    a.id='a'
    ETS4UDiv.appendChild(a)
 
    var link=document.createTextNode("Guide to speculative fiction")
    a.appendChild(link)
    a.href = "https://www.masterclass.com/articles/what-is-speculative-fiction-defining-and-understanding-the-different-genres-of-speculative-fiction ";

    var ETS4UDiv=document.createElement('div')
    ETS4UDiv.id='ETS4UDiv'
    resourceDiv.appendChild(ETS4UDiv)
 
    var a=document.createElement('a')
    a.id='a'
    ETS4UDiv.appendChild(a)
 
    var link=document.createTextNode("Guide to reading Utopia")
    a.appendChild(link)
    a.href = "https://www.masterclass.com/articles/what-is-utopian-literature";

    var ETS4UDiv=document.createElement('div')
    ETS4UDiv.id='ETS4UDiv'
    resourceDiv.appendChild(ETS4UDiv)
 
    var a=document.createElement('a')
    a.id='a'
    ETS4UDiv.appendChild(a)
 
    var link=document.createTextNode("ISU book ideas")
    a.appendChild(link)
    a.href = "http://iss.scdsb.on.ca/Documents/Library%20Documents/Senior-ISU-Book-ListWEB.pdf ";
 
}

function EWC4U(){
 
    var EWC4UDiv=document.createElement('div')
    EWC4UDiv.id='EWC4UDiv'
    resourceDiv.appendChild(EWC4UDiv)
 
    var a=document.createElement('a')
    a.id='a'
    EWC4UDiv.appendChild(a)
 
    var link=document.createTextNode("Writing tools overview")
    a.appendChild(link)
    a.href = "https://dcripe.files.wordpress.com/2014/06/50-writing-tools.pdf ";
 
    var EWC4UDiv=document.createElement('div')
    EWC4UDiv.id='EWC4UDiv'
    resourceDiv.appendChild(EWC4UDiv)
 
    var a=document.createElement('a')
    a.id='a'
    EWC4UDiv.appendChild(a)
 
    var link=document.createTextNode("Guide to narrative writing")
    a.appendChild(link)
    a.href = "https://www.3plearning.com/blog/narrativewriting/";

    var EWC4UDiv=document.createElement('div')
    EWC4UDiv.id='EWC4UDiv'
    resourceDiv.appendChild(EWC4UDiv)
 
    var a=document.createElement('a')
    a.id='a'
    EWC4UDiv.appendChild(a)
 
    var link=document.createTextNode("Informal vs formal writing")
    a.appendChild(link)
    a.href = "https://www.uopeople.edu/blog/formal-vs-informal-writing/";

    var EWC4UDiv=document.createElement('div')
    EWC4UDiv.id='EWC4UDiv'
    resourceDiv.appendChild(EWC4UDiv)
 
    var a=document.createElement('a')
    a.id='a'
    EWC4UDiv.appendChild(a)
 
    var link=document.createTextNode("Poetry guide")
    a.appendChild(link)
    a.href = "http://www.teachenglishtoday.org/wp-content/uploads/2018/07/Notes-on-Grade-12-HL-poems-2.pdf";
 
}

function FSF4U(){
 
    var FSF4UDiv=document.createElement('div')
    FSF4UDiv.id='FSF4UDiv'
    resourceDiv.appendChild(FSF4UDiv)
 
    var a=document.createElement('a')
    a.id='a'
    FSF4UDiv.appendChild(a)
 
    var link=document.createTextNode("Francophonie overview")
    a.appendChild(link)
    a.href = "https://www.moyak.com/papers/history-francophonie.html ";
 
    var FSF4UDiv=document.createElement('div')
    FSF4UDiv.id='FSF4UDiv'
    resourceDiv.appendChild(FSF4UDiv)
 
    var a=document.createElement('a')
    a.id='a'
    FSF4UDiv.appendChild(a)
 
    var link=document.createTextNode("French Social Media guide")
    a.appendChild(link)
    a.href = "https://www.fluentin3months.com/french-social-media/ ";

    var FSF4UDiv=document.createElement('div')
    FSF4UDiv.id='FSF4UDiv'
    resourceDiv.appendChild(FSF4UDiv)
 
    var a=document.createElement('a')
    a.id='a'
    FSF4UDiv.appendChild(a)
 
    var link=document.createTextNode("Guide to french culture")
    a.appendChild(link)
    a.href = "https://www.bestoffrance.ca/post/beginners-guide-to-french-culture ";

    var FSF4UDiv=document.createElement('div')
    FSF4UDiv.id='FSF4UDiv'
    resourceDiv.appendChild(FSF4UDiv)
 
    var a=document.createElement('a')
    a.id='a'
    FSF4UDiv.appendChild(a)
 
    var link=document.createTextNode("Quizlet")
    a.appendChild(link)
    a.href = "https://quizlet.com/ca/484031276/fsf4u-vocab-flash-cards/ ";
 
}

function MCV4U(){
 
    var MCV4UDiv=document.createElement('div')
    MCV4UDiv.id='MCV4UDiv'
    resourceDiv.appendChild(MCV4UDiv)
 
    var a=document.createElement('a')
    a.id='a'
    MCV4UDiv.appendChild(a)
 
    var link=document.createTextNode("Intro to Dervivatives")
    a.appendChild(link)
    a.href = "https://www.mathsisfun.com/calculus/derivatives-introduction.html";
 
    var MCV4UDiv=document.createElement('div')
    MCV4UDiv.id='MCV4UDiv'
    resourceDiv.appendChild(MCV4UDiv)
 
    var a=document.createElement('a')
    a.id='a'
    MCV4UDiv.appendChild(a)
 
    var link=document.createTextNode("Intro to Vectors")
    a.appendChild(link)
    a.href = "http://www1.maths.leeds.ac.uk/~smt/TEACHING/MATH2620/revision.pdf";

    var MCV4UDiv=document.createElement('div')
    MCV4UDiv.id='MCV4UDiv'
    resourceDiv.appendChild(MCV4UDiv)
 
    var a=document.createElement('a')
    a.id='a'
    MCV4UDiv.appendChild(a)
 
    var link=document.createTextNode("Intro to planes")
    a.appendChild(link)
    a.href = "https://tutorial.math.lamar.edu/classes/calciii/eqnsofplanes.aspx";
 
    var MCV4UDiv=document.createElement('div')
    MCV4UDiv.id='MCV4UDiv'
    resourceDiv.appendChild(MCV4UDiv)
 
    var a=document.createElement('a')
    a.id='a'
    MCV4UDiv.appendChild(a)
 
    var link=document.createTextNode("Intro to exponential functions")
    a.appendChild(link)
    a.href = "https://opentextbc.ca/calculusv1openstax/chapter/exponential-and-logarithmic-functions/ ";
 
}
MCV4U()






